service: aws-node-mongodb

provider:
  name: aws
  runtime: nodejs10.x

functions:
#  Create
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: product
          method: post
          cors: true
# Read
  products:
    handler: handler.products
    events:
      - http:
          path: user
          method: get
          cors: true

# Update
  updateProduct:
    handler: handler.updateProduct
    events:
      - http:
          path: product/{id}
          method: put
          cors: true

# Delete
  deleteProduct:
    handler: handler.deleteProduct
    events:
      - http:
          path: product/{id}
          method: delete
          cors: true
